financial_schemas = {
    "income": """
        CREATE TABLE IF NOT EXISTS income (
            symbol_id BIGINT NOT NULL,
            ticker TEXT,
            date DATE NOT NULL,
            report_type TEXT NOT NULL,
            reportedCurrency TEXT,
            totalRevenue FLOAT, costOfRevenue FLOAT, grossProfit FLOAT,
            costofGoodsAndServicesSold FLOAT, operatingIncome FLOAT,
            operatingExpenses FLOAT, ebit FLOAT, ebitda FLOAT, netIncome FLOAT,
            sellingGeneralAndAdministrative FLOAT, researchAndDevelopment FLOAT,
            depreciation FLOAT, depreciationAndAmortization FLOAT,
            incomeBeforeTax FLOAT, incomeTaxExpense FLOAT, effectiveTaxRate FLOAT,
            netInterestIncome FLOAT, interestIncome FLOAT, interestExpense FLOAT,
            interestAndDebtExpense FLOAT, investmentIncomeNet FLOAT,
            nonInterestIncome FLOAT, otherNonOperatingIncome FLOAT,
            netIncomeFromContinuingOperations FLOAT, comprehensiveIncomeNetOfTax FLOAT,
            revGrowth FLOAT, ebitGrowth FLOAT, ebitMargin FLOAT,
            capexPctRevenue FLOAT, nwcPctRevenue FLOAT, daPctRevenue FLOAT, ROIC FLOAT,
            UNIQUE(symbol_id, date, report_type)
        );
        CREATE INDEX IF NOT EXISTS idx_income_symbol_id ON income(symbol_id);
    """,
    "balance": """
        CREATE TABLE IF NOT EXISTS balance (
            symbol_id BIGINT NOT NULL,
            ticker TEXT,
            date DATE NOT NULL,
            report_type TEXT NOT NULL,
            reportedCurrency TEXT,
            totalCurrentAssets FLOAT,
            cashAndCashEquivalentsAtCarryingValue FLOAT,
            cashAndShortTermInvestments FLOAT,
            inventory FLOAT,
            currentNetReceivables FLOAT,
            shortTermInvestments FLOAT,
            otherCurrentAssets FLOAT,
            totalNonCurrentAssets FLOAT,
            propertyPlantEquipment FLOAT,
            accumulatedDepreciationAmortizationPPE FLOAT,
            intangibleAssets FLOAT,
            intangibleAssetsExcludingGoodwill FLOAT,
            goodwill FLOAT,
            investments FLOAT,
            longTermInvestments FLOAT,
            otherNonCurrentAssets FLOAT,
            totalAssets FLOAT,
            totalCurrentLiabilities FLOAT,
            currentAccountsPayable FLOAT,
            deferredRevenue FLOAT,
            currentDebt FLOAT,
            shortTermDebt FLOAT,
            otherCurrentLiabilities FLOAT,
            totalNonCurrentLiabilities FLOAT,
            capitalLeaseObligations FLOAT,
            longTermDebt FLOAT,
            currentLongTermDebt FLOAT,
            longTermDebtNoncurrent FLOAT,
            shortLongTermDebtTotal FLOAT,
            otherNonCurrentLiabilities FLOAT,
            totalLiabilities FLOAT,
            totalShareholderEquity FLOAT,
            treasuryStock FLOAT,
            retainedEarnings FLOAT,
            commonStock FLOAT,
            commonStockSharesOutstanding FLOAT,
            NWC FLOAT,
            deltaNWC FLOAT,
            nwcRatio FLOAT,
            UNIQUE(symbol_id, date, report_type)
        );

        CREATE INDEX IF NOT EXISTS idx_balance_symbol_id ON balance(symbol_id);
            """,
    "cash": """
        CREATE TABLE IF NOT EXISTS cash (
            symbol_id BIGINT NOT NULL,
            ticker TEXT,
            date DATE NOT NULL,
            report_type TEXT NOT NULL,
            reportedCurrency TEXT,
            operatingCashflow FLOAT,
            paymentsForOperatingActivities FLOAT,
            proceedsFromOperatingActivities FLOAT,
            changeInOperatingLiabilities FLOAT,
            changeInOperatingAssets FLOAT,
            depreciationDepletionAndAmortization FLOAT,
            changeInReceivables FLOAT,
            changeInInventory FLOAT,
            stockBasedCompensation FLOAT,
            netIncome FLOAT,
            profitLoss FLOAT,
            cashflowFromInvestment FLOAT,
            capitalExpenditures FLOAT,
            cashflowFromFinancing FLOAT,
            proceedsFromRepaymentsOfShortTermDebt FLOAT,
            paymentsForRepurchaseOfCommonStock FLOAT,
            paymentsForRepurchaseOfEquity FLOAT,
            paymentsForRepurchaseOfPreferredStock FLOAT,
            dividendPayout FLOAT,
            dividendPayoutCommonStock FLOAT,
            dividendPayoutPreferredStock FLOAT,
            proceedsFromIssuanceOfCommonStock FLOAT,
            proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet FLOAT,
            proceedsFromIssuanceOfPreferredStock FLOAT,
            proceedsFromRepurchaseOfEquity FLOAT,
            proceedsFromSaleOfTreasuryStock FLOAT,
            changeInCashAndCashEquivalents FLOAT,
            changeInExchangeRate FLOAT,
            FCF FLOAT,
            FCF_YoY_Growth FLOAT,
            FCF_Per_Share FLOAT,
            FCFF FLOAT,

            UNIQUE(symbol_id, date, report_type)
        );

        CREATE INDEX IF NOT EXISTS idx_cash_symbol_id ON cash(symbol_id);
            """,
    "earnings": """
        CREATE TABLE IF NOT EXISTS earnings (
            symbol_id BIGINT NOT NULL,
            ticker TEXT,
            date DATE NOT NULL,
            report_type TEXT NOT NULL,
            reportedDate TEXT,
            reportTime TEXT,
            reportedEPS TEXT,
            estimatedEPS TEXT,
            surprise TEXT,
            surprisePercentage TEXT,

            UNIQUE(symbol_id, date, report_type)
        );

        CREATE INDEX IF NOT EXISTS idx_earnings_symbol_id ON earnings(symbol_id);
            """,
    "overview": """
       CREATE TABLE IF NOT EXISTS overview (
            symbol_id INTEGER NOT NULL,
            Symbol TEXT NOT NULL,
            AssetType TEXT,
            Name TEXT,
            Description TEXT,
            CIK TEXT,
            Exchange TEXT,
            Currency TEXT,
            Country TEXT,
            Sector TEXT,
            Industry TEXT,
            Address TEXT,
            FiscalYearEnd TEXT,
            LatestQuarter TEXT,
            MarketCapitalization BIGINT,
            EBITDA BIGINT,
            SharesOutstanding BIGINT,
            SharesFloat BIGINT,
            PERatio FLOAT,
            PEGRatio FLOAT,
            TrailingPE FLOAT,
            ForwardPE FLOAT,
            PriceToSalesRatioTTM FLOAT,
            PriceToBookRatio FLOAT,
            EVToRevenue FLOAT,
            EVToEBITDA FLOAT,
            BookValue FLOAT,
            DividendPerShare FLOAT,
            DividendYield FLOAT,
            DividendDate FLOAT,
            ExDividendDate FLOAT,
            dividendPrice REAL,
            EPS FLOAT,
            DilutedEPSTTM FLOAT,
            RevenuePerShareTTM FLOAT,
            ProfitMargin FLOAT,
            OperatingMarginTTM FLOAT,
            ReturnOnAssetsTTM FLOAT,
            ReturnOnEquityTTM FLOAT,
            RevenueTTM BIGINT,
            GrossProfitTTM BIGINT,
            QuarterlyEarningsGrowthYOY FLOAT,
            QuarterlyRevenueGrowthYOY FLOAT,
            AnalystTargetPrice FLOAT,
            AnalystRatingStrongBuy BIGINT,
            AnalystRatingBuy BIGINT,
            AnalystRatingHold BIGINT,
            AnalystRatingSell BIGINT,
            AnalystRatingStrongSell BIGINT,
            Beta FLOAT,
            "52WeekHigh" FLOAT,
            "52WeekLow" FLOAT,
            "50DayMovingAverage" FLOAT,
            "200DayMovingAverage" FLOAT,
            PercentInsiders FLOAT,
            PercentInstitutions FLOAT,
            CostOfEquity REAL,
            WACC REAL,
            IntrinsicPrice REAL,
            intrinsic_price REAL,
            roic REAL,
            sloanRatio REAL,
            timestamp REAL,

            -- Constraints
            UNIQUE(symbol_id)
        );

        CREATE INDEX IF NOT EXISTS idx_overview_symbol_id ON overview(symbol_id);
            """,
}
